### ISSUE TITLE
Search Bar Layout

### ISSUE THREAD

**Issue by dev-saad808** [saad6742988/WeatherBuddy#18]
### Search Bar Dropdown List

Dropdown is occupying full space even if the list is short. It's height must be wrap content.

**Comment by dev-saad808** [comment]
### Issue:
`SearchBar` Composable is designed to occupy entire screen when it is active.

### Solution:
`DockedSearchBar` will resolve the issue it changes is it's height with recpect to Items in the list.

**Comment by saad6742988** [comment]
Now, the DockedSearchBar pushes the other Content to down when it's list is opened in active state

![ScreenShot](https://github.com/saad6742988/WeatherBuddy/assets/72674691/0bb5f9d6-e17b-44b2-b00f-f4b46387d918)

**Comment by saad6742988** [comment]
Now, DockedSearchBar pushes the other content to down when it gets active and list is opened.
![Screenshot](https://github.com/saad6742988/WeatherBuddy/assets/72674691/014e332d-86a0-4f2d-bcf2-f5b3507a68fa)

**Comment by dev-saad808** [comment]
Now, DockedSearchBar pushes the other content to down when it gets active and list is opened.

![Screenshot](https://github.com/saad6742988/WeatherBuddy/assets/72674691/93ec5cb4-df62-4c0f-ad58-fe7ee4c90915)

**Comment by dev-saad808** [comment]
### Issue:
Content below Search Bar was constrainted to it's bottom in Contraint layout.

### Solution:
Added a guideline from top with some margin and other content is attached to that guideline instead of SearchBar.
