### ISSUE TITLE
Null States for Cities

### ISSUE THREAD

**Issue by dev-saad808** [saad6742988/WeatherBuddy#25]
Open weather city search api gives list of city with their state and country, But some cities do not have states so it shows null.

![image](https://github.com/user-attachments/assets/3d8a217a-7aa3-4e7b-b02e-e46cfbee0b21)

**Comment by saad6742988** [comment]
This Issue is resolved in Pull Request #27

**Comment by dev-saad808** [comment]
This Issue is resolved in Pull Request #27.
